### ISSUE TITLE
issue on new install

### ISSUE THREAD

**Issue by cjmick** [robbiebarrat/twitter-contest-enterer#22]
`╰─$ python TwitterBot.py

Searching again

Traceback (most recent call last):
  File "TwitterBot.py", line 70, in <module>
    run()
  File "TwitterBot.py", line 65, in run
    search(api.search(q=key))
  File "/usr/lib/python3.7/site-packages/tweepy-3.6.0-py3.7.egg/tweepy/binder.py", line 250, in _call
  File "/usr/lib/python3.7/site-packages/tweepy-3.6.0-py3.7.egg/tweepy/binder.py", line 234, in execute
tweepy.error.TweepError: [{'code': 32, 'message': 'Could not authenticate you.'}]

Not sure what the issue is, only info I changed were the keys
`

**Comment by Hypris** [comment]
I ran into the same problem. Changed the keys still didnt work
